---
- hosts: wordpress-ec2
  become: true
  gather_facts: no
  tasks:
    - name: Upgrade all packages
      yum:
        name: "*"
        state: latest
    - name: Install apache and mysql
      ansible.builtin.yum:
        name: 
          - httpd
          - mysql
    - name: Download wordpress
      unarchive:
        src:  https://wordpress.org/latest.tar.gz
        dest: /home/ec2-user
        remote_src: yes
    - name: copying file with playbook
      copy:
        src: ~/wordpress/wp-config-sample.php
        dest: ~/wordpress/wp-config.php
